# Generated by Django 3.2.4 on 2021-07-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('business_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('dashboard_name', models.CharField(max_length=100)),
                ('dashboard_description', models.CharField(max_length=200)),
                ('dashboard_link', models.CharField(max_length=200)),
                ('dashboard_tag', models.CharField(max_length=300)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('dashboard_owner', models.CharField(max_length=100)),
                ('internal_only', models.BooleanField(default=False)),
                ('dashboard_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page_register.source')),
                ('dashboars_business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page_register.businessunit')),
            ],
        ),
    ]
