# Generated by Django 3.2.4 on 2021-09-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='dashboard_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='dashboard_owner',
            field=models.EmailField(max_length=100),
        ),
    ]
